@startuml
'https://plantuml.com/sequence-diagram

autonumber
home_page  ->  contact:首页，切换到通讯录页

contact  ->  add_member:点击添加成员，切换到添加成员页

add_member  --> eadit_contact:点击收到输入，切换到编辑联系人页

eadit_contact  --> add_member:保存，返回添加成员页

@enduml